Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - activerecord-update.gemspec
    - spec/**/*_spec.rb

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
